// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // IMPORTANT: Use DIRECT_URL (port 5432, session mode) here — NOT DATABASE_URL.
    // prisma.config.ts datasource.url is ONLY used by the CLI (migrate deploy, etc).
    // PgBouncer (port 6543) hangs on advisory locks during migrations.
    // The runtime PrismaClient uses DATABASE_URL via the pg adapter in db.ts separately.
    // Falls back to DATABASE_URL if DIRECT_URL is not set (e.g., on Railway where both point to the same DB).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
